# config/_default/menus.toml

# Navigation Links
# To link a homepage widget, set url to "#<widget-file-name>" from content/home/

[[main]]
  name = "About"
  url  = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url  = "#publications"
  weight = 20

#[[main]]
#  name = "Projects"
#  url  = "#projects"
#  weight = 30

[[main]]
  name = "Contact"
  url  = "#contact"
  weight = 60

# Link to a PDF CV. Make sure the file exists at static/files/cv.pdf
[[main]]
  name = "CV"
  url  = "files/cv.pdf"
  weight = 70
